"""Stable Django-specific public API surface."""

from .db import (
    DatabaseDayOverrideProvider,
    DatabaseHolidayProvider,
    apply_database_holiday_overrides,
    apply_database_overrides,
)
from .models import CalendarDayOverride, CalendarDayOverrideWindow, CalendarHoliday
from .services import (
    activate_calendar_day_override,
    activate_calendar_holiday,
    build_calendar,
    deactivate_calendar_day_override,
    deactivate_calendar_holiday,
    delete_calendar_day_override,
    delete_calendar_holiday,
    get_calendar,
    get_calendar_day_override,
    get_calendar_day_override_windows,
    get_calendar_holiday,
    get_default_calendar,
    list_calendar_day_override_windows,
    list_calendar_day_overrides,
    list_calendar_holiday_days,
    list_calendar_holidays,
    list_configured_calendars,
    now,
    reset_calendar_cache,
    set_calendar_day_override,
    set_calendar_holiday,
    sync_calendar_day_overrides,
    sync_calendar_holidays,
)

__all__ = [
    "CalendarDayOverride",
    "CalendarDayOverrideWindow",
    "CalendarHoliday",
    "DatabaseDayOverrideProvider",
    "DatabaseHolidayProvider",
    "activate_calendar_day_override",
    "activate_calendar_holiday",
    "apply_database_holiday_overrides",
    "apply_database_overrides",
    "build_calendar",
    "deactivate_calendar_day_override",
    "deactivate_calendar_holiday",
    "delete_calendar_day_override",
    "delete_calendar_holiday",
    "get_calendar",
    "get_calendar_day_override",
    "get_calendar_day_override_windows",
    "get_calendar_holiday",
    "get_default_calendar",
    "list_calendar_day_overrides",
    "list_calendar_day_override_windows",
    "list_calendar_holiday_days",
    "list_calendar_holidays",
    "list_configured_calendars",
    "now",
    "reset_calendar_cache",
    "set_calendar_day_override",
    "set_calendar_holiday",
    "sync_calendar_day_overrides",
    "sync_calendar_holidays",
]
