# Generated by Codex for django-bizcal.

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):  # type: ignore[misc]
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="CalendarHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calendar_name", models.CharField(db_index=True, max_length=100)),
                ("day", models.DateField(db_index=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "calendar holiday",
                "verbose_name_plural": "calendar holidays",
                "ordering": ("calendar_name", "day"),
            },
        ),
        migrations.AddConstraint(
            model_name="calendarholiday",
            constraint=models.UniqueConstraint(
                fields=("calendar_name", "day"),
                name="bizcal_unique_calendar_holiday_day",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarholiday",
            index=models.Index(
                fields=("calendar_name", "day"),
                name="bizcal_holiday_calendar_day_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calendarholiday",
            index=models.Index(
                fields=("calendar_name", "is_active"),
                name="bizcal_holiday_calendar_active_idx",
            ),
        ),
    ]
