# Generated by Codex for django-bizcal.

from __future__ import annotations

from django.db import migrations, models
from django.db.models import F, Q


class Migration(migrations.Migration):  # type: ignore[misc]
    dependencies = [
        ("django_bizcal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarDayOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calendar_name", models.CharField(db_index=True, max_length=100)),
                ("day", models.DateField(db_index=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "calendar day override",
                "verbose_name_plural": "calendar day overrides",
                "ordering": ("calendar_name", "day"),
            },
        ),
        migrations.CreateModel(
            name="CalendarDayOverrideWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "override",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="windows",
                        to="django_bizcal.calendardayoverride",
                    ),
                ),
            ],
            options={
                "verbose_name": "calendar day override window",
                "verbose_name_plural": "calendar day override windows",
                "ordering": ("override", "position", "start_time", "end_time", "pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="calendardayoverride",
            constraint=models.UniqueConstraint(
                fields=("calendar_name", "day"),
                name="bizcal_unique_calendar_day_override_day",
            ),
        ),
        migrations.AddIndex(
            model_name="calendardayoverride",
            index=models.Index(
                fields=("calendar_name", "day"),
                name="bizcal_day_override_calendar_day_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calendardayoverride",
            index=models.Index(
                fields=("calendar_name", "is_active"),
                name="bizcal_day_override_calendar_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendardayoverridewindow",
            constraint=models.CheckConstraint(
                condition=Q(end_time__gt=F("start_time")),
                name="bizcal_day_override_window_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendardayoverridewindow",
            constraint=models.UniqueConstraint(
                fields=("override", "position"),
                name="bizcal_unique_day_override_window_position",
            ),
        ),
    ]
