# Generated by Claude for django-bizcal.

from __future__ import annotations

import django
from django.db import migrations, models
from django.db.models import F, Q

_CHECK_CONSTRAINT_ARG = "condition" if django.VERSION >= (5, 1) else "check"


class Migration(migrations.Migration):  # type: ignore[misc]
    dependencies = [
        ("django_bizcal", "0002_day_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendardayoverridewindow",
            name="end_offset_days",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0 for an intraday window, 1 when the window ends on the next day.",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="calendardayoverridewindow",
            name="bizcal_day_override_window_start_before_end",
        ),
        migrations.AddConstraint(
            model_name="calendardayoverridewindow",
            constraint=models.CheckConstraint(
                **{
                    _CHECK_CONSTRAINT_ARG: Q(
                        end_offset_days=0,
                        end_time__gt=F("start_time"),
                    )
                    | Q(end_offset_days=1, end_time__lte=F("start_time")),
                    "name": "bizcal_day_override_window_start_before_end",
                }
            ),
        ),
    ]
